name: RSSHub Docs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: RSSNext/rsshub-docs
        ref: main

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js Active LTS
      uses: actions/setup-node@v5
      with:
        node-version: lts/*
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build RSSHub Docs
      run: pnpm docs:build

    - name: Upload RSSHub Docs artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./.vitepress/dist

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: .vitepress/dist
        keep_history: false
      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
